var mainMenu;
var pluginRootDir = null;

// Bootstrap Lifecycle
function startup(data, reason) {
    pluginRootDir = data.installPath || data.rootDir;
    Zotero.debug("Better OCR: Startup (v" + data.version + ")");
    addToAllWindows();
}

function shutdown(data, reason) {
    pluginRootDir = null;
	removeFromAllWindows();
}

function install() {}
function uninstall() {}

// UI Helpers
function alertUser(title, msg) {
    let win = Zotero.getMainWindow();
    if (win) {
        win.alert(title + "\n\n" + msg);
    } else {
        var prompts = Components.classes["@mozilla.org/embedcomp/prompt-service;1"]
                        .getService(Components.interfaces.nsIPromptService);
        prompts.alert(null, title, msg);
    }
}

function addToWindow(win) {
	let doc = win.document;
	let menu = doc.getElementById('zotero-itemmenu');
	if (!menu) return;

    let existing = doc.getElementById('better-ocr-menu-item');
    if (existing) existing.remove();

    let menuItem;
    if (doc.createXULElement) {
        menuItem = doc.createXULElement('menuitem');
    } else {
        menuItem = doc.createElementNS('http://www.mozilla.org/keymaster/gatekeeper/there.is.only.xul', 'menuitem');
    }

	menuItem.setAttribute('id', 'better-ocr-menu-item');
	menuItem.setAttribute('label', 'Extract Text (Better OCR)');
	menuItem.setAttribute('class', 'menuitem-iconic');
	menuItem.addEventListener('command', performOCR, false);
	
	menu.appendChild(menuItem);
	mainMenu = menuItem;
}

function addToAllWindows() {
	let windows = Zotero.getMainWindows();
	for (let win of windows) {
		addToWindow(win);
	}
}

function removeFromAllWindows() {
	let windows = Zotero.getMainWindows();
	for (let win of windows) {
		let doc = win.document;
		let menuItem = doc.getElementById('better-ocr-menu-item');
		if (menuItem) menuItem.remove();
	}
}

var windowListener = {
	onOpenWindow: function (xulWin) {
		let win = xulWin.QueryInterface(Components.interfaces.nsIInterfaceRequestor)
						.getInterface(Components.interfaces.nsIDOMWindow);
		win.addEventListener("load", function () {
			win.removeEventListener("load", arguments.callee, false);
			addToWindow(win);
		}, false);
	},
	onCloseWindow: function (xulWin) {},
	onWindowTitleChange: function (xulWin, newTitle) {}
};

// Core Logic
async function performOCR() {
    if (!pluginRootDir) {
        alertUser("Better OCR Error", "Plugin root path is missing. Please restart Zotero.");
        return;
    }

	var items = Zotero.getActiveZoteroPane().getSelectedItems();
    if (!items.length) return;

    let pdfItems = [];
	for (let item of items) {
		if (item.isAttachment() && item.attachmentContentType == 'application/pdf') {
		
pdfItems.push(item);
		} else if (item.isRegularItem()) {
			let attachment = await item.getAttachment();
			if (attachment && attachment.attachmentContentType == 'application/pdf') {
			
pdfItems.push(attachment);
			}
		}
	}

    if (pdfItems.length === 0) {
        alertUser("Better OCR", "No valid PDF attachments found in selection.");
        return;
    }

    let pw = new Zotero.ProgressWindow();
    pw.changeHeadline("Better OCR");
    pw.show();
    let prog = new pw.ItemProgress("chrome://zotero/skin/tick.png", "Initializing...");
    prog.setProgress(0);

	try {
        let count = 0;
		for (let attachmentItem of pdfItems) {
            count++;
            let title = attachmentItem.getField('title') || "Unknown";
            prog.setText(`Processing ${count}/${pdfItems.length}: ${title.substring(0, 30)}...`);
            prog.setProgress((count / pdfItems.length) * 100);
            
			await processItem(attachmentItem);
		}
        prog.setText("OCR Complete.");
        pw.startCloseTimer(3000);
	} catch (e) {
		Zotero.logError(e);
        prog.setError();
        prog.setText("Error: " + e);
	}
}

async function processItem(attachmentItem) {
	let pdfPath = await attachmentItem.getFilePathAsync();
	if (!pdfPath) {
        Zotero.debug("Better OCR Skip: No path for item " + attachmentItem.id);
        return;
    }

	try {
		await runBundledExecutable(pdfPath);
		
		let txtPath = pdfPath.substring(0, pdfPath.lastIndexOf('.')) + ".txt";
		
		if (await IOUtils.exists(txtPath)) {
			let content = await IOUtils.readUTF8(txtPath);
			let parentItem = Zotero.Items.get(attachmentItem.parentID);
			let targetID = parentItem ? parentItem.id : attachmentItem.id;
			
			let note = new Zotero.Item('note');
			note.parentID = targetID;
			let cleanText = content.replace(/</g, "&lt;").replace(/>/g, "&gt;");
            
            let timestamp = new Date().toLocaleString();
			note.setNote(`<h1>OCR Extraction</h1><p><i>Generated by Better OCR on ${timestamp}</i></p><hr/><pre>${cleanText}</pre>`);
			await note.saveTx();
			
			await IOUtils.remove(txtPath);
            Zotero.debug("Better OCR: Success for " + pdfPath);
		} else {
            throw new Error("Engine finished but no text file created. Check permissions or Poppler errors.");
        }
	} catch (e) {
		throw e;
	}
}

function runBundledExecutable(pdfPath) {
	return new Promise((resolve, reject) => {
        if (!pluginRootDir) return reject("Plugin root dir lost");

        let exeFile = pluginRootDir.clone();
        exeFile.append("bin");
        
        var xulRuntime = Components.classes["@mozilla.org/xre/app-info;1"]
                           .getService(Components.interfaces.nsIXULRuntime);
        
        if (xulRuntime.OS == "WINNT") {
            exeFile.append("BetterOCR_Tool.exe");
        } else {
            exeFile.append("BetterOCR_Tool");
        }

        if (!exeFile.exists()) {
            return reject("Embedded Engine not found at: " + exeFile.path);
        }
        
        if (xulRuntime.OS != "WINNT") {
            try { exeFile.permissions |= 0o755; } catch(e) {}
        }

		let process = Components.classes["@mozilla.org/process/util;1"]
						.createInstance(Components.interfaces.nsIProcess);
		process.init(exeFile);
		let args = [pdfPath];

		process.runAsync(args, args.length, {
			observe: function(subject, topic, data) {
				if (topic === "process-finished") resolve();
				else reject("Engine execution failed (Code: " + data + ")");
			}
		});
	});
}
